name:                typelevel-rewrite-rules
version:             1.0
synopsis:            Solve type equalities using custom type-level rewrite rules
description:         A typechecker plugin which allows the user to specify a set of domain-specific rewrite rules. These get applied whenever the compiler is unable to solve a type equality constraint, in the hope that the rewritten equality constraint will be easier to solve.
homepage:            https://github.com/gelisam/typelevel-rewrite-rules#readme
github:              gelisam/typelevel-rewrite-rules
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Type System
extra-source-files:
- README.md
- CHANGELOG.md

# for development
#ghc-options: -W -Wall -dcore-lint

# for release
ghc-options: -W -Wall

dependencies:
  - base >= 4.12 && < 5
  - ghc-prim >= 0.5.3

library:
  source-dirs:      src
  dependencies:
    - ghc >= 8.10.2 && <= 9.1
    - containers >= 0.6.2.1
    - term-rewriting >= 0.3.0.1
    - transformers >= 0.5.6.2
  default-extensions:  CPP

tests:
  should-compile:
    source-dirs: test/should-compile
    main: Test.hs
    dependencies:
      - typelevel-rewrite-rules
      - vinyl >= 0.13.0

  # can't run "stack test error-messages", it locks a file which prevents the
  # test from running stack on its test packages.
  #error-messages:
  #  source-dirs: test/error-messages
  #  main: Test.hs
