name: CI

on:
  # Build every pull request, to check for regressions.
  pull_request:

  # Build when a PR is merged, to update the README's CI badge.
  push:
    branches: [main]

  # Build once a month, to detect missing upper bounds.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  error-messages:
    name: Error Messages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Use the stable versions of the dependencies, as error messages are
          # too likely to have subtle changes between versions.
          - ghc: "8.10"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      name: Setup Stack and Cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true

    - uses: actions/cache@v2
      name: Cache Stack and Cabal Artifacts
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
          ~/.stack
          **/.stack-work
        key: ${{ runner.os }}-{{ matrix.ghx }}-error-messages-${{ hashFiles('stack.yaml') }}

    - name: Test Error Messages
      run: |
        ./test/error-messages/Test.hs `pwd`

