name: CI

on:
  # Build every pull request, to check for regressions.
  pull_request:

  # Build when a PR is merged, to update the README's CI badge.
  push:
    branches: [main]

  # Build once a month, to detect missing upper bounds.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  error-messages:
    name: Error Messages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Use the stable versions of the dependencies, as error messages are
          # too likely to have subtle changes between versions.
          - ghc: "8.10"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    # ./test/error-messages/Test.hs is a cabal script, so we need Cabal.
    - uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      name: Setup Cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: false

    # ./test/error-messages/Test.hs runs some stack projects, so we also need stack.
    - uses: actions/setup-haskell@v1
      id: setup-haskell-stack
      name: Setup Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true

    - uses: actions/cache@v2
      id: cache-stack-and-cabal
      name: Cache Stack and Cabal Artifacts
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
          ~/.stack
          **/.stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-error-messages-${{ hashFiles('stack.yaml') }}

    # For some reason setup-haskell-cabal sometimes doesn't run 'cabal update'.
    - name: Initialize Cabal
      if: steps.cache-stack-and-cabal.outputs.cache-hit != 'true'
      run: |
        cabal update

    - name: Test Error Messages
      run: |
        ./test/error-messages/Test.hs `pwd`

