name: CI

on:
  # Build every pull request, to check for regressions.
  pull_request:

  # Build when a PR is merged, to update the README's CI badge.
  push:
    branches: [main]

  # Build once a month, to detect missing upper bounds.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  stack:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Check that the build passes with the recommended snapshot.
          - name: stable
            stack_yaml: "stack.yaml"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      id: setup-haskell-stack
      name: Setup Stack
      with:
        enable-stack: true
        stack-setup-ghc: true
        stack-no-global: true
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v1
      name: Cache Stack Artifacts
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles(matrix.stack_yaml) }}

    # This test is separate because it cannot run inside stack test.
    # It's pointless to run it more than once because its lts is hardcoded.
    - name: Test Error Messages
      if: matrix.name == 'stable'
      run: |
        stack --system-ghc ./test/error-messages/Test.hs
